version: '3'

services:
  app:
    build: ./docker/app
    depends_on:
      - postgres-postgis
    volumes:
      - .:/var/www/html:cached
  nginx:
    image: nginx
    ports:
      - 3333:80
    depends_on:
      - app
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  postgres-postgis:
    image: mdillon/postgis:10
    ports:
      - 54310:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ~/docker/${APP_NAME}/postgres:/var/lib/postgresql/data
      - ./docker/db:/docker-entrypoint-initdb.d
  
